<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Olivia Robertson" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>project2</title>
    <meta name="generator" content="Hugo 0.61.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/about/">ABOUT</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2.knit/">project2</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              <div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(tidyr)
<span style="color:#a6e22e">library</span>(ggplot2)
<span style="color:#a6e22e">library</span>(dplyr)
</code></pre></div><pre><code>## 
## Attaching package: 'dplyr'
</code></pre><pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag
</code></pre><pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(tibble)
<span style="color:#a6e22e">library</span>(MASS)
</code></pre></div><pre><code>## 
## Attaching package: 'MASS'
</code></pre><pre><code>## The following object is masked from 'package:dplyr':
## 
##     select
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(lmtest)
</code></pre></div><pre><code>## Loading required package: zoo
</code></pre><pre><code>## 
## Attaching package: 'zoo'
</code></pre><pre><code>## The following objects are masked from 'package:base':
## 
##     as.Date, as.Date.numeric
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(plotROC) 
<span style="color:#a6e22e">library</span>(boot)
<span style="color:#a6e22e">library</span>(glmnet)
</code></pre></div><pre><code>## Loading required package: Matrix
</code></pre><pre><code>## 
## Attaching package: 'Matrix'
</code></pre><pre><code>## The following objects are masked from 'package:tidyr':
## 
##     expand, pack, unpack
</code></pre><pre><code>## Loaded glmnet 3.0-1
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(sandwich)
</code></pre></div><p>##Introduction
My dataset includes patient information on physician office visits from the package Ecdat. The variables included in this dataset are &ldquo;ofp&rdquo; number of physician office visits, &ldquo;ofnp&rdquo; number of nonphysician office visits, &ldquo;opp&rdquo; number of physician outpatient visits, &ldquo;opnp&rdquo; number of nonphysician outpatient visits, &ldquo;emr&rdquo; number of emergency room visits, &ldquo;hosp&rdquo; number of hospitalizations, &ldquo;numchron&rdquo; number of chronic conditions, binary &ldquo;adldiff&rdquo; if the person has a condition that limits activities of daily living, &ldquo;age&rdquo; age in years (divided by 10), binary &ldquo;black&rdquo; if the person african–american, &ldquo;sex&rdquo; if the person is male or female, binary &ldquo;married&rdquo; if the person is married, &ldquo;school&rdquo; number of years of education, &ldquo;faminc&rdquo; family income in $10000, binary &ldquo;employed&rdquo; if the person employed, binary &ldquo;privins&rdquo; if the person covered by private health insurance, binary &ldquo;medicaid&rdquo; is the person covered by medicaid, &ldquo;region&rdquo; the region (northeast, midwest,west, other), and &ldquo;hlth&rdquo; self-perceived health (excellent, poor, other).</p>
<p>The purpose of this project is to determine variables with and without interaction that account for if an individual has a condition that limits activities of daily living.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">visits <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">read.csv</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">OFP.csv&#34;</span>)
<span style="color:#a6e22e">head</span>(visits)
</code></pre></div><pre><code>##   X ofp ofnp opp opnp emr hosp numchron adldiff age black    sex maried
## 1 1   5    0   0    0   0    1        2       0 6.9   yes   male    yes
## 2 2   1    0   2    0   2    0        2       0 7.4    no female    yes
## 3 3  13    0   0    0   3    3        4       1 6.6   yes female     no
## 4 4  16    0   5    0   1    1        2       1 7.6    no   male    yes
## 5 5   3    0   0    0   0    0        2       1 7.9    no female    yes
## 6 6  17    0   0    0   0    0        5       1 6.6    no female     no
##   school faminc employed privins medicaid region  hlth
## 1      6 2.8810      yes     yes       no  other other
## 2     10 2.7478       no     yes       no  other other
## 3     10 0.6532       no      no      yes  other  poor
## 4      3 0.6588       no     yes       no  other  poor
## 5      6 0.6588       no     yes       no  other other
## 6      7 0.3301       no      no      yes  other  poor
</code></pre><p>##MANOVA</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Normality</span>
<span style="color:#a6e22e">ggplot</span>(visits, <span style="color:#a6e22e">aes</span>(x <span style="color:#f92672">=</span> ofp, y <span style="color:#f92672">=</span> numchron)) <span style="color:#f92672">+</span>
 <span style="color:#a6e22e">geom_point</span>(alpha <span style="color:#f92672">=</span> <span style="color:#ae81ff">.5</span>) <span style="color:#f92672">+</span> <span style="color:#a6e22e">geom_density_2d</span>(h<span style="color:#f92672">=</span><span style="color:#ae81ff">2</span>) <span style="color:#f92672">+</span> <span style="color:#a6e22e">coord_fixed</span>() <span style="color:#f92672">+</span> <span style="color:#a6e22e">facet_wrap</span>(<span style="color:#f92672">~</span>region)
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Homogeneity</span>
covmats<span style="color:#f92672">&lt;-</span>visits<span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">group_by</span>(region)<span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">do</span>(covs<span style="color:#f92672">=</span><span style="color:#a6e22e">cov</span>(.[2<span style="color:#f92672">:</span><span style="color:#ae81ff">3</span>]))
<span style="color:#a6e22e">for</span>(i in <span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">3</span>){<span style="color:#a6e22e">print</span>(covmats<span style="color:#f92672">$</span>covs[i])}
</code></pre></div><pre><code>## [[1]]
##            ofp      ofnp
## ofp  40.582725  6.319781
## ofnp  6.319781 37.474543
## 
## [[1]]
##           ofp     ofnp
## ofp  54.43531 16.08302
## ofnp 16.08302 31.62989
## 
## [[1]]
##            ofp      ofnp
## ofp  43.491422  5.260384
## ofnp  5.260384 16.457533
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#MANOVA</span>
man1<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">manova</span>(<span style="color:#a6e22e">cbind</span>(ofp,opp,emr,hosp,numchron,age,school,faminc)<span style="color:#f92672">~</span>region, data<span style="color:#f92672">=</span>visits)
<span style="color:#a6e22e">summary</span>(man1)
</code></pre></div><pre><code>##             Df   Pillai approx F num Df den Df    Pr(&gt;F)    
## region       3 0.044757    8.324     24  13191 &lt; 2.2e-16 ***
## Residuals 4402                                              
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Univariate ANOVA</span>
<span style="color:#a6e22e">summary.aov</span>(man1)
</code></pre></div><pre><code>##  Response ofp :
##               Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## region         3    583 194.286   4.262 0.005164 **
## Residuals   4402 200669  45.586                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
##  Response opp :
##               Df Sum Sq Mean Sq F value Pr(&gt;F)
## region         3      3   1.136  0.0851 0.9682
## Residuals   4402  58771  13.351               
## 
##  Response emr :
##               Df  Sum Sq Mean Sq F value Pr(&gt;F)
## region         3    1.92 0.63973  1.2923 0.2752
## Residuals   4402 2179.15 0.49504               
## 
##  Response hosp :
##               Df  Sum Sq Mean Sq F value Pr(&gt;F)
## region         3    0.78 0.26003  0.4666 0.7056
## Residuals   4402 2453.29 0.55731               
## 
##  Response numchron :
##               Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## region         3   26.3  8.7558  4.8194 0.002368 **
## Residuals   4402 7997.5  1.8168                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
##  Response age :
##               Df  Sum Sq Mean Sq F value Pr(&gt;F)
## region         3    0.19 0.06341  0.1579 0.9246
## Residuals   4402 1767.10 0.40143               
## 
##  Response school :
##               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## region         3   1941  647.07  47.766 &lt; 2.2e-16 ***
## Residuals   4402  59633   13.55                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
##  Response faminc :
##               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## region         3    507 169.017  20.016 6.989e-13 ***
## Residuals   4402  37171   8.444                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#t-tests</span>
<span style="color:#a6e22e">pairwise.t.test</span>(visits<span style="color:#f92672">$</span>ofp,visits<span style="color:#f92672">$</span>region,
 p.adj<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">none&#34;</span>)
</code></pre></div><pre><code>## 
## 	Pairwise comparisons using t tests with pooled SD 
## 
## data:  visits$ofp and visits$region 
## 
##         midwest noreast other 
## noreast 0.0258  -       -     
## other   0.5152  0.0740  -     
## west    0.0020  0.4080  0.0069
## 
## P value adjustment method: none
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">pairwise.t.test</span>(visits<span style="color:#f92672">$</span>opp,visits<span style="color:#f92672">$</span>region,
 p.adj<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">none&#34;</span>)
</code></pre></div><pre><code>## 
## 	Pairwise comparisons using t tests with pooled SD 
## 
## data:  visits$opp and visits$region 
## 
##         midwest noreast other
## noreast 0.62    -       -    
## other   0.76    0.80    -    
## west    0.87    0.76    0.92 
## 
## P value adjustment method: none
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">pairwise.t.test</span>(visits<span style="color:#f92672">$</span>emr,visits<span style="color:#f92672">$</span>region,
 p.adj<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">none&#34;</span>)
</code></pre></div><pre><code>## 
## 	Pairwise comparisons using t tests with pooled SD 
## 
## data:  visits$emr and visits$region 
## 
##         midwest noreast other
## noreast 0.647   -       -    
## other   0.076   0.264   -    
## west    0.171   0.393   0.903
## 
## P value adjustment method: none
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">pairwise.t.test</span>(visits<span style="color:#f92672">$</span>hosp,visits<span style="color:#f92672">$</span>region,
 p.adj<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">none&#34;</span>)
</code></pre></div><pre><code>## 
## 	Pairwise comparisons using t tests with pooled SD 
## 
## data:  visits$hosp and visits$region 
## 
##         midwest noreast other
## noreast 0.37    -       -    
## other   0.87    0.27    -    
## west    0.87    0.33    0.98 
## 
## P value adjustment method: none
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">pairwise.t.test</span>(visits<span style="color:#f92672">$</span>numchron,visits<span style="color:#f92672">$</span>region,
 p.adj<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">none&#34;</span>)
</code></pre></div><pre><code>## 
## 	Pairwise comparisons using t tests with pooled SD 
## 
## data:  visits$numchron and visits$region 
## 
##         midwest noreast other  
## noreast 0.64740 -       -      
## other   0.00053 0.00814 -      
## west    0.36993 0.67854 0.03307
## 
## P value adjustment method: none
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">pairwise.t.test</span>(visits<span style="color:#f92672">$</span>age,visits<span style="color:#f92672">$</span>region,
 p.adj<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">none&#34;</span>)
</code></pre></div><pre><code>## 
## 	Pairwise comparisons using t tests with pooled SD 
## 
## data:  visits$age and visits$region 
## 
##         midwest noreast other
## noreast 0.62    -       -    
## other   0.71    0.85    -    
## west    0.89    0.56    0.64 
## 
## P value adjustment method: none
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">pairwise.t.test</span>(visits<span style="color:#f92672">$</span>school,visits<span style="color:#f92672">$</span>region,
 p.adj<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">none&#34;</span>)
</code></pre></div><pre><code>## 
## 	Pairwise comparisons using t tests with pooled SD 
## 
## data:  visits$school and visits$region 
## 
##         midwest noreast other  
## noreast 0.65    -       -      
## other   7.2e-09 2.1e-06 -      
## west    3.0e-10 3.5e-10 &lt; 2e-16
## 
## P value adjustment method: none
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">pairwise.t.test</span>(visits<span style="color:#f92672">$</span>faminc,visits<span style="color:#f92672">$</span>region,
 p.adj<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">none&#34;</span>)
</code></pre></div><pre><code>## 
## 	Pairwise comparisons using t tests with pooled SD 
## 
## data:  visits$faminc and visits$region 
## 
##         midwest noreast other  
## noreast 0.2079  -       -      
## other   0.0019  3.4e-05 -      
## west    6.7e-06 0.0024  5.0e-14
## 
## P value adjustment method: none
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#bonferroni </span>
<span style="color:#ae81ff">1</span><span style="color:#ae81ff">+8</span><span style="color:#ae81ff">+48</span>
</code></pre></div><pre><code>## [1] 57
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#ae81ff">0.05</span><span style="color:#f92672">/</span><span style="color:#ae81ff">57</span>
</code></pre></div><pre><code>## [1] 0.000877193
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Type I Error calc</span>
<span style="color:#ae81ff">1</span> <span style="color:#f92672">-</span> <span style="color:#ae81ff">0.95</span>^57
</code></pre></div><pre><code>## [1] 0.9462665
</code></pre><p>It is likely that independent observations were made but it isn't known if this is a random sample. It might not be likely that homogeneity, multicollinearity, linear relationships among dependent variables and multivariance were met. I do not expect there to be extreme uni- or multivariaant outliers.</p>
<p>Assuming that the data passes the MANOVA assumptions, our hypothesis is that the numeric variables have equal means of the group for the categorical variable region. I left out the numeric variables number of nonphysician office visits and number of nonphysician outpatient visits because it would be redundant with number of physician office visits and number of physician outpatient visits included.</p>
<p>The MANOVA found that there is significantly different means among the numeric variables for region (p-value &laquo; 0.05). The bonferroni adjustment was made to control Type I error to correct alpha to 0.000877193 where from the follow up univariate ANOVA tests school and family income variables were found to have significantly mean difference across regions (p-value &lt; 0.00088).</p>
<p>Post hoc analysis was done for pairwise comparisons of the significant variables to find what regions differed in number of years of school and family income. Only the midwest and north east regions not significantly differ in means for number of years in school. The midwest and west, other and north east, and west and other were the regions that significantly differed in family income. This analysis was done according to the bonferroni adjustment for multiple comparisons.</p>
<p>A total of 57 tests were done for this analysis (1 MANOVA, 8 ANOVA and 48 t-tests). There is a 0.9462 probability of at least one Type I error.  The bonferroni test kept the error rate at 0.05 by  adjusting to 0.00088 as discussed.</p>
<p>##Randomization Test</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#null distribution</span>
visits <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">ggplot</span>(<span style="color:#a6e22e">aes</span>(faminc,fill<span style="color:#f92672">=</span>privins))<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_histogram</span>(bins<span style="color:#f92672">=</span><span style="color:#ae81ff">6.5</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">facet_wrap</span>(<span style="color:#f92672">~</span>privins) <span style="color:#f92672">+</span> <span style="color:#a6e22e">xlab</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Family Income ($10,000)&#34;</span>) <span style="color:#f92672">+</span> <span style="color:#a6e22e">ggtitle</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Private Insurance for Family Incomes&#34;</span>)
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#mean diff</span>
visits <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">group_by</span>(privins) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">summarize</span>(means<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(faminc)) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">summarize</span>(<span style="color:#a6e22e">diff</span>(means))
</code></pre></div><pre><code>## # A tibble: 1 x 1
##   `diff(means)`
##           &lt;dbl&gt;
## 1          1.11
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#randomization</span>
<span style="color:#a6e22e">set.seed</span>(<span style="color:#ae81ff">348</span>)

rand_dist<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">vector</span>()
<span style="color:#a6e22e">for</span>(i in <span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">5000</span>){
rand<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">data.frame</span>(income<span style="color:#f92672">=</span><span style="color:#a6e22e">sample</span>(visits<span style="color:#f92672">$</span>faminc),insurance<span style="color:#f92672">=</span>visits<span style="color:#f92672">$</span>privins)
rand_dist[i]<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">mean</span>(rand[rand<span style="color:#f92672">$</span>insurance<span style="color:#f92672">==</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">yes&#34;</span>,]<span style="color:#f92672">$</span>income)<span style="color:#f92672">-</span>
 <span style="color:#a6e22e">mean</span>(rand[rand<span style="color:#f92672">$</span>insurance<span style="color:#f92672">==</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">no&#34;</span>,]<span style="color:#f92672">$</span>income)}

<span style="color:#75715e">#p-value</span>
<span style="color:#a6e22e">mean</span>(rand_dist<span style="color:#f92672">&gt;</span><span style="color:#ae81ff">1.112961</span>)<span style="color:#f92672">*</span><span style="color:#ae81ff">2</span>
</code></pre></div><pre><code>## [1] 0
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#t-test</span>
<span style="color:#a6e22e">t.test</span>(data<span style="color:#f92672">=</span>visits,faminc<span style="color:#f92672">~</span>privins)
</code></pre></div><pre><code>## 
## 	Welch Two Sample t-test
## 
## data:  faminc by privins
## t = -13.842, df = 2659.1, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.270625 -0.955296
## sample estimates:
##  mean in group no mean in group yes 
##          1.662984          2.775944
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">{<span style="color:#a6e22e">hist</span>(rand_dist,main<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Test Statistic Distribution&#34;</span>,ylab<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Frequency&#34;</span>,xlim <span style="color:#f92672">=</span> <span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">-.4</span>,<span style="color:#ae81ff">1.2</span>)); <span style="color:#a6e22e">abline</span>(v <span style="color:#f92672">=</span> <span style="color:#ae81ff">1.112961</span>,col<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">red&#34;</span>)}
</code></pre></div><p><!-- raw HTML omitted -->
The null hypothesis for this randomization test is that mean family income is the same for 
individuals with and without private insurance. The alternate hypothesis is that mean family income is different across individuals with and withouot private insurance.</p>
<p>##Linear Regression Model</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#fit with interaction</span>
visits<span style="color:#f92672">$</span>ofp_c<span style="color:#f92672">&lt;-</span>visits<span style="color:#f92672">$</span>ofp<span style="color:#f92672">-</span><span style="color:#a6e22e">mean</span>(visits<span style="color:#f92672">$</span>ofp)
visits<span style="color:#f92672">$</span>faminc_c<span style="color:#f92672">&lt;-</span>visits<span style="color:#f92672">$</span>faminc<span style="color:#f92672">-</span><span style="color:#a6e22e">mean</span>(visits<span style="color:#f92672">$</span>faminc)
fit <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(numchron <span style="color:#f92672">~</span> ofp_c<span style="color:#f92672">*</span>maried<span style="color:#f92672">*</span>faminc_c, data<span style="color:#f92672">=</span>visits)
<span style="color:#a6e22e">summary</span>(fit)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = numchron ~ ofp_c * maried * faminc_c, data = visits)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.2727 -1.0343 -0.3119  0.6588  6.7424 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               1.589926   0.031457  50.543   &lt;2e-16 ***
## ofp_c                     0.046633   0.004478  10.414   &lt;2e-16 ***
## mariedyes                -0.066920   0.041479  -1.613   0.1067    
## faminc_c                  0.005960   0.014866   0.401   0.6885    
## ofp_c:mariedyes           0.006964   0.006037   1.154   0.2487    
## ofp_c:faminc_c           -0.004273   0.001902  -2.246   0.0247 *  
## mariedyes:faminc_c       -0.031087   0.016807  -1.850   0.0644 .  
## ofp_c:mariedyes:faminc_c  0.005468   0.002346   2.331   0.0198 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.301 on 4398 degrees of freedom
## Multiple R-squared:  0.07292,	Adjusted R-squared:  0.07144 
## F-statistic: 49.42 on 7 and 4398 DF,  p-value: &lt; 2.2e-16
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Plot</span>
<span style="color:#a6e22e">ggplot</span>(visits, <span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span>ofp_c, y<span style="color:#f92672">=</span>numchron,group<span style="color:#f92672">=</span>maried))<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_point</span>(<span style="color:#a6e22e">aes</span>(color<span style="color:#f92672">=</span>maried))<span style="color:#f92672">+</span>
 <span style="color:#a6e22e">geom_smooth</span>(method<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">lm&#34;</span>,formula<span style="color:#f92672">=</span>y<span style="color:#f92672">~</span><span style="color:#ae81ff">1</span>,se<span style="color:#f92672">=</span>F,fullrange<span style="color:#f92672">=</span>T,<span style="color:#a6e22e">aes</span>(color<span style="color:#f92672">=</span>maried))<span style="color:#f92672">+</span><span style="color:#a6e22e">xlab</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Family Income ($10,000)&#34;</span>) <span style="color:#f92672">+</span> <span style="color:#a6e22e">ylab</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Number of  Chronic Illnesses&#34;</span>) <span style="color:#f92672">+</span><span style="color:#a6e22e">ggtitle</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Number of Chronic Illnesses by Family Income&#34;</span>)
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Assumptions</span>
resids<span style="color:#f92672">&lt;-</span>fit<span style="color:#f92672">$</span>residuals; fitvals<span style="color:#f92672">&lt;-</span>fit<span style="color:#f92672">$</span>fitted.values
<span style="color:#a6e22e">ggplot</span>()<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_point</span>(<span style="color:#a6e22e">aes</span>(fitvals,resids))<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_hline</span>(yintercept<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>, col<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">red&#34;</span>)
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">bptest</span>(fit)
</code></pre></div><pre><code>## 
## 	studentized Breusch-Pagan test
## 
## data:  fit
## BP = 120.01, df = 7, p-value &lt; 2.2e-16
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">ggplot</span>()<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_histogram</span>(<span style="color:#a6e22e">aes</span>(resids),bins<span style="color:#f92672">=</span><span style="color:#ae81ff">20</span>)
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">ggplot</span>()<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_qq</span>(<span style="color:#a6e22e">aes</span>(sample<span style="color:#f92672">=</span>resids))<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_qq_line</span>()
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">ks.test</span>(resids, <span style="color:#e6db74">&#34;</span><span style="color:#e6db74">pnorm&#34;</span>, sd<span style="color:#f92672">=</span><span style="color:#a6e22e">sd</span>(resids))
</code></pre></div><pre><code>## Warning in ks.test(resids, &quot;pnorm&quot;, sd = sd(resids)): ties should not be
## present for the Kolmogorov-Smirnov test
</code></pre><pre><code>## 
## 	One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.13155, p-value &lt; 2.2e-16
## alternative hypothesis: two-sided
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#robust standard errors</span>
<span style="color:#a6e22e">summary</span>(fit)<span style="color:#f92672">$</span>coef[,<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">2</span>]
</code></pre></div><pre><code>##                              Estimate  Std. Error
## (Intercept)               1.589925786 0.031456758
## ofp_c                     0.046633493 0.004477811
## mariedyes                -0.066920123 0.041479153
## faminc_c                  0.005960421 0.014865905
## ofp_c:mariedyes           0.006963694 0.006036566
## ofp_c:faminc_c           -0.004272970 0.001902349
## mariedyes:faminc_c       -0.031087335 0.016806799
## ofp_c:mariedyes:faminc_c  0.005467513 0.002345572
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">coeftest</span>(fit, vcov <span style="color:#f92672">=</span> <span style="color:#a6e22e">vcovHC</span>(fit))[,<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">2</span>]
</code></pre></div><pre><code>##                              Estimate  Std. Error
## (Intercept)               1.589925786 0.033875220
## ofp_c                     0.046633493 0.006720185
## mariedyes                -0.066920123 0.043389741
## faminc_c                  0.005960421 0.017991131
## ofp_c:mariedyes           0.006963694 0.009382407
## ofp_c:faminc_c           -0.004272970 0.002789926
## mariedyes:faminc_c       -0.031087335 0.020341280
## ofp_c:mariedyes:faminc_c  0.005467513 0.003488509
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#fit w/o interaction</span>
fit2 <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(numchron <span style="color:#f92672">~</span> ofp_c<span style="color:#f92672">+</span>maried<span style="color:#f92672">+</span>faminc_c, data<span style="color:#f92672">=</span>visits)
<span style="color:#a6e22e">summary</span>(fit2)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = numchron ~ ofp_c + maried + faminc_c, data = visits)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.3095 -1.0708 -0.3061  0.6535  6.8883 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.569889   0.029633  52.977  &lt; 2e-16 ***
## ofp_c        0.052171   0.002901  17.982  &lt; 2e-16 ***
## mariedyes   -0.051094   0.040695  -1.256  0.20935    
## faminc_c    -0.019085   0.006927  -2.755  0.00589 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.301 on 4402 degrees of freedom
## Multiple R-squared:  0.07104,	Adjusted R-squared:  0.07041 
## F-statistic: 112.2 on 3 and 4402 DF,  p-value: &lt; 2.2e-16
</code></pre><p>This linear regression used number of chronic illnesses as the response variable and mean centered physician's office visits. marital status and family income as the predictors with interaction. The intercept, 1.59, is the predicted number of chronic illnessess when physician's office visits and family income is 0 USD and unmarried. While holding marriage status and family income constant, for every 1 increase centered physician's office visits the number of chronic illnesses is expected to increase by 0.0466. While holding physician's office visits and family income constant, a married individudal will have 0.0669 less chronic illnesses than a person who isn't married. While holding physician's office visits and marital status constant, for every $1 increase in centered family income, the number of chronic illnessess will increase by 0.00596. The expected physicians office visits for non-married individuals is 0.006964 more than for those who are married. Family income is expected to be 0.0311 USD less for nonmarried people than married people. For each increase in physicians office vist, family income is expected to decrease by 0.004273 USD. For individuals who are not married, with each increase of physician's office visits, family income is expected to increase 0.005458 USD more than for those who are married with each increase of physician's office vists.</p>
<p>This data does not pass linearity, homoskedasticity, or normality.</p>
<p>Using robust standard error, the coefficients did not change. The SE's increased with robust standard errors.</p>
<p>This model explains 7.292% of the variation in the outcome.</p>
<p>When running the model without interaction, one of the predictors (family income) is now significant.</p>
<p>##Bootstrapped Standard Errors of Linear Regression Model</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">samp_distn<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">replicate</span>(<span style="color:#ae81ff">5000</span>, {
 boot_dat<span style="color:#f92672">&lt;-</span>boot_dat<span style="color:#f92672">&lt;-</span>visits<span style="color:#a6e22e">[sample</span>(<span style="color:#a6e22e">nrow</span>(visits),replace<span style="color:#f92672">=</span><span style="color:#66d9ef">TRUE</span>),]
 fit3<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">lm</span>(numchron <span style="color:#f92672">~</span> faminc_c <span style="color:#f92672">*</span> maried<span style="color:#f92672">*</span>ofp_c, data<span style="color:#f92672">=</span>boot_dat)
 <span style="color:#a6e22e">coef</span>(fit3)
})

samp_distn<span style="color:#f92672">%&gt;%</span>t<span style="color:#f92672">%&gt;%</span>as.data.frame<span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">summarize_all</span>(sd)
</code></pre></div><pre><code>##   (Intercept)   faminc_c mariedyes      ofp_c faminc_c:mariedyes
## 1  0.03338738 0.01741327 0.0427156 0.00653458          0.0195547
##   faminc_c:ofp_c mariedyes:ofp_c faminc_c:mariedyes:ofp_c
## 1    0.002683802     0.009085953              0.003286179
</code></pre><p>The bootstrapped standard errors are much more similar to the robust standard errors than the original, however they are slightly less. 
##Logistic Regression</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#regression</span>
fit4<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">glm</span>(adldiff<span style="color:#f92672">~</span>ofp_c<span style="color:#f92672">+</span>faminc_c,data<span style="color:#f92672">=</span>visits,family<span style="color:#f92672">=</span><span style="color:#a6e22e">binomial</span>(link<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">logit&#34;</span>))
<span style="color:#a6e22e">coeftest</span>(fit4)
</code></pre></div><pre><code>## 
## z test of coefficients:
## 
##               Estimate Std. Error  z value  Pr(&gt;|z|)    
## (Intercept) -1.4128048  0.0392614 -35.9846 &lt; 2.2e-16 ***
## ofp_c        0.0352047  0.0050362   6.9904 2.741e-12 ***
## faminc_c    -0.1358598  0.0204638  -6.6390 3.158e-11 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">exp</span>(<span style="color:#a6e22e">coef</span>(fit4))
</code></pre></div><pre><code>## (Intercept)       ofp_c    faminc_c 
##   0.2434595   1.0358317   0.8729650
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#confusion matrix</span>
visits<span style="color:#f92672">$</span>prob<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">predict</span>(fit4,type<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">response&#34;</span>) 
<span style="color:#a6e22e">table</span>(predict<span style="color:#f92672">=</span><span style="color:#a6e22e">as.numeric</span>(visits<span style="color:#f92672">$</span>prob<span style="color:#f92672">&gt;</span><span style="color:#ae81ff">.5</span>),truth<span style="color:#f92672">=</span>visits<span style="color:#f92672">$</span>adldiff)<span style="color:#f92672">%&gt;%</span>addmargins
</code></pre></div><pre><code>##        truth
## predict    0    1  Sum
##     0   3492  890 4382
##     1     15    9   24
##     Sum 3507  899 4406
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Accuracy</span>
(<span style="color:#ae81ff">3492</span><span style="color:#ae81ff">+9</span>)<span style="color:#f92672">/</span><span style="color:#ae81ff">4406</span>
</code></pre></div><pre><code>## [1] 0.7945983
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Sensitivity (TPR)</span>
<span style="color:#ae81ff">9</span><span style="color:#f92672">/</span><span style="color:#ae81ff">899</span>
</code></pre></div><pre><code>## [1] 0.01001112
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Specificity (TNR)</span>
<span style="color:#ae81ff">3492</span><span style="color:#f92672">/</span><span style="color:#ae81ff">3507</span>
</code></pre></div><pre><code>## [1] 0.9957228
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Recall (PPV)</span>
<span style="color:#ae81ff">9</span><span style="color:#f92672">/</span><span style="color:#ae81ff">24</span>
</code></pre></div><pre><code>## [1] 0.375
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#plot</span>
visits<span style="color:#f92672">$</span>logit<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">predict</span>(fit4) <span style="color:#75715e">#get predicted log-odds</span>
visits<span style="color:#f92672">$</span>outcome<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">factor</span>(visits<span style="color:#f92672">$</span>adldiff,levels<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">0&#34;</span>,<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">1&#34;</span>))
<span style="color:#a6e22e">ggplot</span>(visits,<span style="color:#a6e22e">aes</span>(logit, fill<span style="color:#f92672">=</span>outcome))<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_density</span>(alpha<span style="color:#f92672">=</span><span style="color:#ae81ff">.3</span>)<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">geom_vline</span>(xintercept<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>,lty<span style="color:#f92672">=</span><span style="color:#ae81ff">2</span>)
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#ROC and AUC</span>
ROCplot<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">ggplot</span>(visits)<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_roc</span>(<span style="color:#a6e22e">aes</span>(d<span style="color:#f92672">=</span>adldiff,m<span style="color:#f92672">=</span>prob), n.cuts<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>)<span style="color:#f92672">+</span>
 <span style="color:#a6e22e">geom_segment</span>(<span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>,xend<span style="color:#f92672">=</span><span style="color:#ae81ff">1</span>,y<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>,yend<span style="color:#f92672">=</span><span style="color:#ae81ff">1</span>),lty<span style="color:#f92672">=</span><span style="color:#ae81ff">2</span>)
ROCplot
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">calc_auc</span>(ROCplot)
</code></pre></div><pre><code>##   PANEL group       AUC
## 1     1    -1 0.6262655
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#function</span>
class_diag<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">function</span>(probs,truth){
 tab<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">table</span>(<span style="color:#a6e22e">factor</span>(probs<span style="color:#f92672">&gt;</span><span style="color:#ae81ff">.5</span>,levels<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">FALSE&#34;</span>,<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">TRUE&#34;</span>)),truth)
 acc<span style="color:#f92672">=</span><span style="color:#a6e22e">sum</span>(<span style="color:#a6e22e">diag</span>(tab))<span style="color:#f92672">/</span><span style="color:#a6e22e">sum</span>(tab)
 sens<span style="color:#f92672">=</span>tab[2,<span style="color:#ae81ff">2</span>]<span style="color:#f92672">/</span><span style="color:#a6e22e">colSums</span>(tab)[2]
 spec<span style="color:#f92672">=</span>tab[1,<span style="color:#ae81ff">1</span>]<span style="color:#f92672">/</span><span style="color:#a6e22e">colSums</span>(tab)[1]
 ppv<span style="color:#f92672">=</span>tab[2,<span style="color:#ae81ff">2</span>]<span style="color:#f92672">/</span><span style="color:#a6e22e">rowSums</span>(tab)[2]
 <span style="color:#a6e22e">if</span>(<span style="color:#a6e22e">is.numeric</span>(truth)<span style="color:#f92672">==</span><span style="color:#66d9ef">FALSE</span> <span style="color:#f92672">&amp;</span> <span style="color:#a6e22e">is.logical</span>(truth)<span style="color:#f92672">==</span><span style="color:#66d9ef">FALSE</span>) truth<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">as.numeric</span>(truth)<span style="color:#ae81ff">-1</span>
 <span style="color:#75715e">#CALCULATE EXACT AUC</span>
 ord<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">order</span>(probs, decreasing<span style="color:#f92672">=</span><span style="color:#66d9ef">TRUE</span>)
 probs <span style="color:#f92672">&lt;-</span> probs[ord]; truth <span style="color:#f92672">&lt;-</span> truth[ord]
 TPR<span style="color:#f92672">=</span><span style="color:#a6e22e">cumsum</span>(truth)<span style="color:#f92672">/</span><span style="color:#a6e22e">max</span>(<span style="color:#ae81ff">1</span>,<span style="color:#a6e22e">sum</span>(truth))
 FPR<span style="color:#f92672">=</span><span style="color:#a6e22e">cumsum</span>(<span style="color:#f92672">!</span>truth)<span style="color:#f92672">/</span><span style="color:#a6e22e">max</span>(<span style="color:#ae81ff">1</span>,<span style="color:#a6e22e">sum</span>(<span style="color:#f92672">!</span>truth))
 dup<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">c</span>(probs[<span style="color:#ae81ff">-1</span>]<span style="color:#f92672">&gt;=</span>probs[<span style="color:#f92672">-</span><span style="color:#a6e22e">length</span>(probs)], <span style="color:#66d9ef">FALSE</span>)
 TPR<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">0</span>,TPR[<span style="color:#f92672">!</span>dup],<span style="color:#ae81ff">1</span>); FPR<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">0</span>,FPR[<span style="color:#f92672">!</span>dup],<span style="color:#ae81ff">1</span>)
 n <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">length</span>(TPR)
 auc<span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">sum</span>( ((TPR[<span style="color:#ae81ff">-1</span>]<span style="color:#f92672">+</span>TPR[<span style="color:#f92672">-</span>n])<span style="color:#f92672">/</span><span style="color:#ae81ff">2</span>) <span style="color:#f92672">*</span> (FPR[<span style="color:#ae81ff">-1</span>]<span style="color:#f92672">-</span>FPR[<span style="color:#f92672">-</span>n]) )
 <span style="color:#a6e22e">data.frame</span>(acc,sens,spec,ppv,auc)
} 

<span style="color:#75715e">#CV 10 fold</span>
<span style="color:#a6e22e">set.seed</span>(<span style="color:#ae81ff">1234</span>)
k<span style="color:#f92672">=</span><span style="color:#ae81ff">10</span> 
visitscv<span style="color:#f92672">&lt;-</span>visits<span style="color:#a6e22e">[sample</span>(<span style="color:#a6e22e">nrow</span>(visits)),] 
folds<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">cut</span>(<span style="color:#a6e22e">seq</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#a6e22e">nrow</span>(visits)),breaks<span style="color:#f92672">=</span>k,labels<span style="color:#f92672">=</span>F) 
diags<span style="color:#f92672">&lt;-</span><span style="color:#66d9ef">NULL</span>
<span style="color:#a6e22e">for</span>(i in <span style="color:#ae81ff">1</span><span style="color:#f92672">:</span>k){

 train<span style="color:#f92672">&lt;-</span>visitscv[folds<span style="color:#f92672">!=</span>i,]
 test<span style="color:#f92672">&lt;-</span>visitscv[folds<span style="color:#f92672">==</span>i,]
 truth<span style="color:#f92672">&lt;-</span>test<span style="color:#f92672">$</span>adldiff

 fit5<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">glm</span>(adldiff<span style="color:#f92672">~</span>ofp<span style="color:#f92672">+</span>faminc,data<span style="color:#f92672">=</span>train,family<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">binomial&#34;</span>)
 probs<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">predict</span>(fit5,newdata <span style="color:#f92672">=</span> test,type<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">response&#34;</span>)

 diags<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">rbind</span>(diags,<span style="color:#a6e22e">class_diag</span>(probs,truth))
}
<span style="color:#a6e22e">apply</span>(diags,<span style="color:#ae81ff">2</span>,mean) 
</code></pre></div><pre><code>##         acc        sens        spec         ppv         auc 
## 0.794836116 0.008991227 0.996312405         NaN 0.625437875
</code></pre><p>This logistic regression used the binary variable &ldquo;adldiff&rdquo; as the response variable and mean centered physician's office visits and family income as predictors. When an individual has a family income of 0 and has never visited a physician's office, their odds for having a condition limiting daily activity is 0.2801. While holding family income constant, odds of a condition limiting daily activity decreases 1.0358 with each increase in visit to a physician's office. While holding physician office visits constant, each $10,000 increase in family income decreases the odds of a condition limiting daily activity by 0.1359. All predictors have a p-value less than 0.05, indicating the model is significant.</p>
<p>This model is about 79.46% accurate, however it is important to note, it has an extremely low true positive rate and near perfect true negative rate.</p>
<p>The AUC is close to 0.5, indicating that we can't really predict individuals having a condition that limits their daily activity by family income and physicians office visits. 
##Lasso Regression</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">visitslasso <span style="color:#f92672">&lt;-</span> visits<span style="color:#f92672">%&gt;%</span>dplyr<span style="color:#f92672">::</span><span style="color:#a6e22e">select</span>(<span style="color:#f92672">-</span>prob,<span style="color:#f92672">-</span>outcome,<span style="color:#f92672">-</span>X,<span style="color:#f92672">-</span>logit)
y<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">as.matrix</span>(visitslasso<span style="color:#f92672">$</span>adldiff)
fit6 <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">glm</span>(adldiff<span style="color:#f92672">~</span>.-1, data <span style="color:#f92672">=</span> visitslasso, family <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;</span><span style="color:#e6db74">binomial&#34;</span>)
x<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">model.matrix</span>(fit6)
x<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">scale</span>(x)
cv<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">cv.glmnet</span>(x,y) 
lasso1<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">glmnet</span>(x,y,lambda<span style="color:#f92672">=</span>cv<span style="color:#f92672">$</span>lambda.1se)
<span style="color:#a6e22e">coef</span>(lasso1)
</code></pre></div><pre><code>## 25 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                         s0
## (Intercept)    0.204039946
## ofp            .          
## ofnp           .          
## opp            .          
## opnp           .          
## emr            0.009571913
## hosp           0.001373959
## numchron       0.035682668
## age            0.082327961
## blackno        .          
## blackyes       .          
## sexmale       -0.003289198
## mariedyes     -0.009840636
## school        -0.002073423
## faminc         .          
## employedyes    .          
## privinsyes     .          
## medicaidyes    0.034984107
## regionnoreast  .          
## regionother    .          
## regionwest     .          
## hlthother      .          
## hlthpoor       0.081731447
## ofp_c          .          
## faminc_c       .
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#CV </span>
<span style="color:#a6e22e">set.seed</span>(<span style="color:#ae81ff">1234</span>)
k<span style="color:#f92672">=</span><span style="color:#ae81ff">10</span> 
visitscv2<span style="color:#f92672">&lt;-</span>visitslasso<span style="color:#a6e22e">[sample</span>(<span style="color:#a6e22e">nrow</span>(visitslasso)),] 
folds<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">cut</span>(<span style="color:#a6e22e">seq</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#a6e22e">nrow</span>(visitslasso)),breaks<span style="color:#f92672">=</span>k,labels<span style="color:#f92672">=</span>F) 
diags2<span style="color:#f92672">&lt;-</span><span style="color:#66d9ef">NULL</span>
<span style="color:#a6e22e">for</span>(i in <span style="color:#ae81ff">1</span><span style="color:#f92672">:</span>k){
 train2<span style="color:#f92672">&lt;-</span>visitscv2[folds<span style="color:#f92672">!=</span>i,]
 test2<span style="color:#f92672">&lt;-</span>visitscv2[folds<span style="color:#f92672">==</span>i,]
 truth2<span style="color:#f92672">&lt;-</span>test2<span style="color:#f92672">$</span>adldiff
 fit7<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">glm</span>(adldiff<span style="color:#f92672">~</span>emr<span style="color:#f92672">+</span>hosp<span style="color:#f92672">+</span>numchron<span style="color:#f92672">+</span>age<span style="color:#f92672">+</span>sex<span style="color:#f92672">+</span>maried<span style="color:#f92672">+</span>school<span style="color:#f92672">+</span>medicaid<span style="color:#f92672">+</span>hlth,data<span style="color:#f92672">=</span>train2,family<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">binomial&#34;</span>)
 probs2<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">predict</span>(fit7,newdata <span style="color:#f92672">=</span> test2,type<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">response&#34;</span>)
 diags2<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">rbind</span>(diags2,<span style="color:#a6e22e">class_diag</span>(probs2,truth2))
}
diags2<span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">summarize_all</span>(mean)
</code></pre></div><pre><code>##         acc      sens      spec       ppv       auc
## 1 0.8257045 0.3343958 0.9516561 0.6392141 0.8187942
</code></pre><p>The LASSO regression shows that Emergency room visits, hospital visits, number of chronic illnesses, age, sex, marital status, years in school, medicaid coverage, and self reported health status to be the most important predictors of if an individual has a condition that limits their daily life. Running a 10 fold CV demonstrated a much higher AUC than from the model that only took into account family income and physician's office visits.</p>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
