baseurl = "/"
languageCode = "en-US"
title = "Olivia Robertson"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "olivia.png"
  author = "Olivia Robertson"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "olivrobertson"
  Email         = "olivrobertson@gmail.com"
  Twitter       = "olivrobertson"
  LinkedIn      = "olivrobertson"
 

## Main Menu]
[[menu.main]]
  name = "About"
  identifier = "About"
  weight = 200
  url = "/about/"
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
  

